;; ============================================================================
;; PuTTY-specific key binding
;; ============================================================================

(define-key key-translation-map (kbd "ESC <up>") (kbd "M-<up>"))
(define-key key-translation-map (kbd "ESC <down>") (kbd "M-<down>"))
(define-key key-translation-map (kbd "ESC <deletechar>") (kbd "M-<delete>"))
(define-key key-translation-map (kbd "ESC <prior>") (kbd "M-<prior>"))
(define-key key-translation-map (kbd "ESC <next>") (kbd "M-<next>"))

;; function keys (f11 and f12 don't have unique signals, so I can't use them)
(define-key input-decode-map "\e[11~" (kbd "<f1>"))
(define-key input-decode-map "\e[12~" (kbd "<f2>"))
(define-key input-decode-map "\e[13~" (kbd "<f3>"))
(define-key input-decode-map "\e[14~" (kbd "<f4>"))
(define-key input-decode-map "\e[15~" (kbd "<f5>"))
(define-key input-decode-map "\e[17~" (kbd "<f6>"))
(define-key input-decode-map "\e[18~" (kbd "<f7>"))
(define-key input-decode-map "\e[19~" (kbd "<f8>"))
(define-key input-decode-map "\e[20~" (kbd "<f9>"))
(define-key input-decode-map "\e[21~" (kbd "<f10>"))

;; SHIFT-function (PuTTY doesn't get CTRL-function, so I'm mapping these to <C-fx>)
(define-key input-decode-map "\e[23~" (kbd "<C-f1>"))
(define-key input-decode-map "\e[24~" (kbd "<C-f2>"))
(define-key input-decode-map "\e[25~" (kbd "<C-f3>"))
(define-key input-decode-map "\e[26~" (kbd "<C-f4>"))
(define-key input-decode-map "\e[28~" (kbd "<C-f5>"))
(define-key input-decode-map "\e[29~" (kbd "<C-f6>"))
(define-key input-decode-map "\e[31~" (kbd "<C-f7>"))
(define-key input-decode-map "\e[32~" (kbd "<C-f8>"))
(define-key input-decode-map "\e[33~" (kbd "<C-f9>"))
(define-key input-decode-map "\e[34~" (kbd "<C-f10>"))

;; ALT-function
(define-key input-decode-map "\e\e[11~" (kbd "<M-f1>"))
(define-key input-decode-map "\e\e[12~" (kbd "<M-f2>"))
(define-key input-decode-map "\e\e[13~" (kbd "<M-f3>"))
(define-key input-decode-map "\e\e[14~" (kbd "<M-f4>"))
(define-key input-decode-map "\e\e[15~" (kbd "<M-f5>"))
(define-key input-decode-map "\e\e[17~" (kbd "<M-f6>"))
(define-key input-decode-map "\e\e[18~" (kbd "<M-f7>"))
(define-key input-decode-map "\e\e[19~" (kbd "<M-f8>"))
(define-key input-decode-map "\e\e[20~" (kbd "<M-f9>"))
(define-key input-decode-map "\e\e[21~" (kbd "<M-f10>"))

;; ALT-SHIFT-function (again, mapped to <C-M-fx>)
(define-key input-decode-map "\e\e[23~" (kbd "<C-M-f1>"))
(define-key input-decode-map "\e\e[24~" (kbd "<C-M-f2>"))
(define-key input-decode-map "\e\e[25~" (kbd "<C-M-f3>"))
(define-key input-decode-map "\e\e[26~" (kbd "<C-M-f4>"))
(define-key input-decode-map "\e\e[28~" (kbd "<C-M-f5>"))
(define-key input-decode-map "\e\e[29~" (kbd "<C-M-f6>"))
(define-key input-decode-map "\e\e[31~" (kbd "<C-M-f7>"))
(define-key input-decode-map "\e\e[32~" (kbd "<C-M-f8>"))
(define-key input-decode-map "\e\e[33~" (kbd "<C-M-f9>"))
(define-key input-decode-map "\e\e[34~" (kbd "<C-M-f10>"))

;; keypad
(define-key input-decode-map "\eOp" (kbd "<kp-0>"))
(define-key input-decode-map "\eOq" (kbd "<kp-1>"))
(define-key input-decode-map "\eOr" (kbd "<kp-2>"))
(define-key input-decode-map "\eOs" (kbd "<kp-3>"))
(define-key input-decode-map "\eOt" (kbd "<kp-4>"))
(define-key input-decode-map "\eOu" (kbd "<kp-5>"))
(define-key input-decode-map "\eOv" (kbd "<kp-6>"))
(define-key input-decode-map "\eOw" (kbd "<kp-7>"))
(define-key input-decode-map "\eOx" (kbd "<kp-8>"))
(define-key input-decode-map "\eOy" (kbd "<kp-9>"))
(define-key input-decode-map "\eOn" (kbd "<kp-decimal>"))
(define-key input-decode-map (kbd "M-o m") (kbd "<kp-enter>"))
(define-key input-decode-map "\eOl" (kbd "<kp-add>"))
